source $CONFIGS_DIR/shell/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_STATESEPARATOR=" "

PS1=""

PS1+='\h \u \w $(__git_ps1 "[%s]")'
PS1+="\n$ "

PROMPT_COMMAND="echo"

