. $CONFIGS_DIR/shell/prompt.zsh

## Command history configuration
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

alias rake='noglob rake'
alias git='noglob git'

HISTSIZE=10000
SAVEHIST=10000

# key bindings
# to get these, `echo (CTRL + v, then the key)" | od -c
bindkey "^[[3~" delete-char
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data
