. $CONFIGS_DIR/shell/common.bash

# Load Git completion
zstyle ':completion:*:*:git:*' script $CONFIGS_DIR/zsh/git-completion.zsh
autoload -Uz compinit && compinit

# Custom script from a random internet user, but I like it
source ${CONFIGS_DIR}/zsh/zsh-git-prompt.sh
PROMPT='%m%~%b $(git_super_status) %# '

# ctrl + k, ctrl + a, etc., have issues in tmux with zsh. Fix it.
bindkey -e

export EDITOR=vim

export HISTFILE=$HOME/.zsh_history
SAVEHIST=100000000
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY

